export const API_CONFIG = {
	health: '/api/health',
	frameHealth: '/api/health/frame',
	mediapipeHealth: '/api/health/mediapipe',
	motion: '/api/motion',
	motionGrayscale: '/api/motion/grayscale',
	motionBlur: '/api/motion/blur',
	motionDifference: '/api/motion/difference',
	motionThreshold: '/api/motion/threshold',
	motionContours: '/api/motion/contours',
	motionBoxes: '/api/motion/motion-boxes',
	motionOverlay: '/api/motion/motion-overlay',
	mediapipeFaceBox: '/api/mediapipe/face-box',
	mediapipeFaceMesh: '/api/mediapipe/face-mesh',
	mediapipeFacePose: '/api/mediapipe/head-pose',
	mediapipeHands: '/api/mediapipe/hands',
	mediapipeHandsFingerCounter: '/api/mediapipe/hands/finger-counter',
};
