services:

  frontend:
    image: node:22
    container_name: home-vision-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm start -- --host 0.0.0.0"

  backend:
    image: python:3.12
    container_name: home-vision-backend
    working_dir: /app
    volumes:
      - ./backend:/app
    command: sh -c "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --reload"

  nginx:
    image: nginx:latest
    container_name: home-vision-nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - frontend
      - backend