services:

  frontend:
    build:
      context: ./frontend
    container_name: home-vision-frontend

  backend:
    build:
      context: ./backend
    container_name: home-vision-backend
    ports:
      - "8000:8000"

  nginx:
    build:
      context: ./docker/nginx
    container_name: home-vision-nginx
    ports:
      - "8443:443"
    depends_on:
      - frontend
      - backend
