# Default Nginx configuration file for the Docker container.
# This configuration sets up a reverse proxy to forward requests to the frontend and backend services.
# The frontend service is expected to be running on port 4200, and the backend service on port 8080.
# The Nginx server listens on port 80 and routes requests based on the URL path.

server {
	listen 80;
	location / {
		proxy_pass http://frontend:4200;
	}
	location /api {
		proxy_pass http://backend:8080;
	}
}