# Default Nginx configuration file for the Docker container.
# This configuration forwards browser requests to the Angular dev server.
# The backend is exposed directly on port 8000 by docker-compose.

server {
	listen 443 ssl;
	ssl_certificate /etc/nginx/certs/nginx.crt;
	ssl_certificate_key /etc/nginx/certs/nginx.key;
	location /api/ {
		proxy_pass http://backend:8000;
		proxy_set_header Host $host;
	}

	location / {
		proxy_pass http://frontend:4200;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
		proxy_set_header Host $host;
	}
}
